name: "🐛 Bug Report"
description: Report a bug or unexpected behavior in Apex Circle
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug!
        Please fill out the sections below to help us understand and fix the issue quickly.

  - type: dropdown
    id: affected-component
    attributes:
      label: Affected Component
      description: Which part of the platform is affected?
      options:
        - Community Website (Frontend)
        - Desktop Admin App
        - Backend API
        - Documentation
        - CI/CD / GitHub Actions
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Recordings
      description: If applicable, add screenshots or screen recordings to help explain the issue.
      placeholder: Drag and drop images here or paste links...
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - 🟢 Low — Minor visual or non-blocking issue
        - 🟡 Medium — Feature partially broken, workaround exists
        - 🟠 High — Feature is broken, no workaround
        - 🔴 Critical — App crashes, data loss, or security issue
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Which browser are you using?
      placeholder: "e.g., Chrome 120, Firefox 121, Safari 17"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "e.g., Windows 11, macOS Sonoma, Ubuntu 24.04"
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if applicable)
      description: Output of `node --version`
      placeholder: "e.g., v20.11.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste any relevant log output (console errors, terminal output, etc.)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Add any other context about the problem here...
    validations:
      required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
